// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cm-tooltip': string;
  'inspectHeader': string;
  'inspectTree': string;
}
declare var cssExports: CssExports;
export = cssExports;
