// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'infoCard-container': string;
  'infoCard-docsLink': string;
  'infoCard-evals': string;
  'infoCard-type': string;
}
declare var cssExports: CssExports;
export = cssExports;
