
@baseUrl = http://localhost:3000
@channel= YOUR_CHANNEL
@convoId = YOUR_CONVO_ID

### Send Text
POST {{baseUrl}}/send
Content-Type: application/json

{
  "channel": "{{channel}}",
  "conversationId": "{{convoId}}",
  "payload": {
    "type": "text",
    "text": "Hello this is a text message!"
  }
}

### Send Image
POST {{baseUrl}}/send
Content-Type: application/json

{
  "channel": "{{channel}}",
  "conversationId": "{{convoId}}",
  "payload": {
    "type": "image",
    "title": "ducky duck duck",
    "image": "https://upload.wikimedia.org/wikipedia/commons/a/a1/Mallard2.jpg"
  }
}

### Send Card
POST {{baseUrl}}/send
Content-Type: application/json

{
  "channel": "{{channel}}",
  "conversationId": "{{convoId}}",
  "payload": {
    "type": "card",
    "title": "A banana card",
    "subtitle": "This is a banana",
    "image": "https://upload.wikimedia.org/wikipedia/commons/8/8a/Banana-Single.jpg",
    "actions": [
      {
        "action": "Open URL",
        "title": "Learn more",
        "url": "https://en.wikipedia.org/wiki/Banana"
      },
      {
        "action": "Say something",
        "title": "Say Banana!",
        "text": "Banana!!!"
      },
      {
        "action": "Postback",
        "title": "Post banana",
        "payload": "BANANA"
      }
    ]
  }
}