// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'label': string;
  'zoomLevel': string;
  'zoomToFit': string;
  'zoomWrapper': string;
}
declare var cssExports: CssExports;
export = cssExports;
