@baseUrl = http://localhost:3100
@token = YOUR_TOKEN
@convoId = YOUR_CONVO_ID
@messageId = YOUR_MESSAGE_ID
@userId = YOUR_USER_ID

### Create message
POST {{baseUrl}}/api/messages
Content-Type: application/json
token: {{token}}

{
  "conversationId": "{{convoId}}",
  "authorId": "{{userId}}",
  "payload": {
    "type": "text",
    "text": "hello"
  }
}

### Delete message
DELETE {{baseUrl}}/api/messages?id={{messageId}}
token: {{token}}

### Get message
GET {{baseUrl}}/api/messages/{{messageId}}
token: {{token}}

### List messages
GET {{baseUrl}}/api/messages?conversationId={{convoId}}&limit=100
token: {{token}}