// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'clickable': string;
  'cta_btn': string;
  'cta_tooltip': string;
  'disabled': string;
  'divider': string;
  'item': string;
  'itemSpacing': string;
  'label': string;
  'layoutControls': string;
  'shortcut': string;
  'shortcutLabel': string;
  'tooltip': string;
  'topNav': string;
}
declare var cssExports: CssExports;
export = cssExports;
