// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bp3Input': string;
  'bpEditor': string;
}
declare var cssExports: CssExports;
export = cssExports;
