version: '3.8'

services:
  pg:
    container_name: messaging_pg
    hostname: 'messaging_pg'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '2345:5432'

  redis:
    container_name: messaging_redis
    hostname: 'messaging_redis'
    image: redis
    restart: always
    ports:
      - '9736:6379'
