name: Release
on:
  push:
    branches:
      - sb_teams-single-tenant
  workflow_dispatch:

jobs:
  build_bin:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Fetch Node Packages
        run: |
          yarn --immutable

      - name: Build and Package
        run: |
          yarn build
          yarn package

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: messaging-bin
          path: ./bin/messaging-v*
