name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  messaging:
    name: Publish Messaging Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: messaging

  webchat:
    name: Publish Webchat Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      # Temporarily build the Docker Image of the Webchat
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./packages/webchat/Dockerfile
          push: false
          tags: botpress/webchat:latest
# TODO: Publish image on S3
#      - uses: botpress/gh-actions/build/docker@v1
#        with:
#          repository: webchat
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
