name: Docker
on: [push]
jobs:
  messaging:
    name: Publish Messaging Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: botpress/gh-actions/build/docker@v1
        with:
          repository: messaging
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  webchat:
    name: Publish Webchat Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
# TODO: Publish image on S3
#      - uses: botpress/gh-actions/build/docker@v1
#        with:
#          repository: webchat
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
