name: Docker
on:
  push:
    branches:
      - master
    tags:
      - v*
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  messaging:
    name: Publish Messaging Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: messaging
