name: Pre-Release
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  pre_release_bin:
    name: Build and Publish Binaries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.1'
          cache: 'yarn'

      - name: Install python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install Tools
        run: pip install awscli

      - name: Git Unshallow
        run: git fetch --prune --unshallow

      - name: Fetch Node Packages
        run: yarn

      - name: Build Project
        run: yarn build

      - name: Package Binaries
        run: yarn package

      - name: Extract Informations
        id: info
        uses: botpress/gh-actions/extract_info@master

      - name: Rename Binary Files
        uses: botpress/gh-actions/rename_binaries@master

      - name: Publish Binaries
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync bin s3://botpress-dev-bins/messaging/${{ steps.info.outputs.branch_sanitized }}
