name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:unit --coverage --verbose

  integration:
    name: Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:int --coverage --verbose

  e2e:
    name: E2E
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:e2e --coverage --verbose

  security:
    name: Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:sec --verbose

  migration:
    name: Migration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --frozen-lockfile
      - name: Run tests
        run: |
          yarn test:mig --verbose
