name: Tests
on: [pull_request]
jobs:
  unit:
    name: Unit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: '12.18.3'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn
      - name: Run tests
        run: |
          yarn test --coverage --verbose
