name: Upload
on:
  push:
    branches:
      - master
    paths:
      - 'packages/inject/**'
      - 'packages/components/**'
      - 'packages/webchat/**'
      - 'packages/socket/**'

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

jobs:
  upload_webchat:
    name: Upload Webchat
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/inject
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Fetch Node Packages
        run: |
          yarn --immutable
      - name: Build Webchat
        run: |
          yarn build
          yarn write:version
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS credentials
        with:
          role-to-assume: ${{ secrets.AWS_WEBCHAT_BUCKET_ROLE }}
          role-session-name: messaging_ci_upload_webchat
          aws-region: us-east-1
      - name: Upload Webchat to S3 bucket
        run: |
          # TODO: Change the version (for test purpose)
          aws s3 sync --delete ./dist s3://${{ secrets.AWS_WEBCHAT_BUCKET_NAME }}/v0
